/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaCoreModelsSeverity } from './VTApiPlaneraResaCoreModelsSeverity';
import {
    VTApiPlaneraResaCoreModelsSeverityFromJSON,
    VTApiPlaneraResaCoreModelsSeverityFromJSONTyped,
    VTApiPlaneraResaCoreModelsSeverityToJSON,
} from './VTApiPlaneraResaCoreModelsSeverity';

/**
 * 
 * @export
 * @interface VTApiPlaneraResaCoreModelsNote
 */
export interface VTApiPlaneraResaCoreModelsNote {
    /**
     * 
     * @type {string}
     * @memberof VTApiPlaneraResaCoreModelsNote
     */
    type?: string | null;
    /**
     * 
     * @type {VTApiPlaneraResaCoreModelsSeverity}
     * @memberof VTApiPlaneraResaCoreModelsNote
     */
    severity?: VTApiPlaneraResaCoreModelsSeverity;
    /**
     * 
     * @type {string}
     * @memberof VTApiPlaneraResaCoreModelsNote
     */
    text?: string | null;
}

/**
 * Check if a given object implements the VTApiPlaneraResaCoreModelsNote interface.
 */
export function instanceOfVTApiPlaneraResaCoreModelsNote(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaCoreModelsNoteFromJSON(json: any): VTApiPlaneraResaCoreModelsNote {
    return VTApiPlaneraResaCoreModelsNoteFromJSONTyped(json, false);
}

export function VTApiPlaneraResaCoreModelsNoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaCoreModelsNote {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'severity': !exists(json, 'severity') ? undefined : VTApiPlaneraResaCoreModelsSeverityFromJSON(json['severity']),
        'text': !exists(json, 'text') ? undefined : json['text'],
    };
}

export function VTApiPlaneraResaCoreModelsNoteToJSON(value?: VTApiPlaneraResaCoreModelsNote | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'severity': VTApiPlaneraResaCoreModelsSeverityToJSON(value.severity),
        'text': value.text,
    };
}

