/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VTApiPlaneraResaCoreModelsSeverity = {
    Unknown: 'unknown',
    Low: 'low',
    Normal: 'normal',
    High: 'high'
} as const;
export type VTApiPlaneraResaCoreModelsSeverity = typeof VTApiPlaneraResaCoreModelsSeverity[keyof typeof VTApiPlaneraResaCoreModelsSeverity];


export function VTApiPlaneraResaCoreModelsSeverityFromJSON(json: any): VTApiPlaneraResaCoreModelsSeverity {
    return VTApiPlaneraResaCoreModelsSeverityFromJSONTyped(json, false);
}

export function VTApiPlaneraResaCoreModelsSeverityFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaCoreModelsSeverity {
    return json as VTApiPlaneraResaCoreModelsSeverity;
}

export function VTApiPlaneraResaCoreModelsSeverityToJSON(value?: VTApiPlaneraResaCoreModelsSeverity | null): any {
    return value as any;
}

