/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaCoreModelsNote } from './VTApiPlaneraResaCoreModelsNote';
import {
    VTApiPlaneraResaCoreModelsNoteFromJSON,
    VTApiPlaneraResaCoreModelsNoteFromJSONTyped,
    VTApiPlaneraResaCoreModelsNoteToJSON,
} from './VTApiPlaneraResaCoreModelsNote';
import type { VTApiPlaneraResaCoreModelsTransportMode } from './VTApiPlaneraResaCoreModelsTransportMode';
import {
    VTApiPlaneraResaCoreModelsTransportModeFromJSON,
    VTApiPlaneraResaCoreModelsTransportModeFromJSONTyped,
    VTApiPlaneraResaCoreModelsTransportModeToJSON,
} from './VTApiPlaneraResaCoreModelsTransportMode';
import type { VTApiPlaneraResaCoreModelsTransportSubMode } from './VTApiPlaneraResaCoreModelsTransportSubMode';
import {
    VTApiPlaneraResaCoreModelsTransportSubModeFromJSON,
    VTApiPlaneraResaCoreModelsTransportSubModeFromJSONTyped,
    VTApiPlaneraResaCoreModelsTransportSubModeToJSON,
} from './VTApiPlaneraResaCoreModelsTransportSubMode';
import type { VTApiPlaneraResaWebV4ModelsCoordinateApiModel } from './VTApiPlaneraResaWebV4ModelsCoordinateApiModel';
import {
    VTApiPlaneraResaWebV4ModelsCoordinateApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsCoordinateApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsCoordinateApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsCoordinateApiModel';
import type { VTApiPlaneraResaWebV4ModelsJourneysCallApiModel } from './VTApiPlaneraResaWebV4ModelsJourneysCallApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneysCallApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneysCallApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneysCallApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneysCallApiModel';
import type { VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModel } from './VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModel';

/**
 * Information about a walk, bike or car link between two public transport trip legs.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel {
    /**
     * 
     * @type {VTApiPlaneraResaCoreModelsTransportMode}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel
     */
    transportMode?: VTApiPlaneraResaCoreModelsTransportMode;
    /**
     * 
     * @type {VTApiPlaneraResaCoreModelsTransportSubMode}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel
     */
    transportSubMode?: VTApiPlaneraResaCoreModelsTransportSubMode;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsJourneysCallApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel
     */
    origin?: VTApiPlaneraResaWebV4ModelsJourneysCallApiModel;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsJourneysCallApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel
     */
    destination?: VTApiPlaneraResaWebV4ModelsJourneysCallApiModel;
    /**
     * An ordered list (most important first) of notes related to the access link.
     * @type {Array<VTApiPlaneraResaCoreModelsNote>}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel
     */
    notes?: Array<VTApiPlaneraResaCoreModelsNote> | null;
    /**
     * Distance in meters.
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel
     */
    distanceInMeters?: number | null;
    /**
     * The planned departure time in RFC 3339 format.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel
     */
    plannedDepartureTime?: string | null;
    /**
     * The planned arrival time in RFC 3339 format.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel
     */
    plannedArrivalTime?: string | null;
    /**
     * The planned duration in minutes.
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel
     */
    plannedDurationInMinutes?: number | null;
    /**
     * The estimated departure time in RFC 3339 format, if available.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel
     */
    estimatedDepartureTime?: string | null;
    /**
     * The estimated arrival time in RFC 3339 format, if available.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel
     */
    estimatedArrivalTime?: string | null;
    /**
     * The estimated duration in minutes, if available.
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel
     */
    estimatedDurationInMinutes?: number | null;
    /**
     * Number of steps based on the distance and an estimated step length of 0.65 meters.
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel
     */
    estimatedNumberOfSteps?: number | null;
    /**
     * The coordinates for the link.
     * @type {Array<VTApiPlaneraResaWebV4ModelsCoordinateApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel
     */
    linkCoordinates?: Array<VTApiPlaneraResaWebV4ModelsCoordinateApiModel> | null;
    /**
     * The segments that make up this link.
     * @type {Array<VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel
     */
    segments?: Array<VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModel> | null;
    /**
     * Index of Leg in Journey
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel
     */
    journeyLegIndex?: number;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel {
    return VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transportMode': !exists(json, 'transportMode') ? undefined : VTApiPlaneraResaCoreModelsTransportModeFromJSON(json['transportMode']),
        'transportSubMode': !exists(json, 'transportSubMode') ? undefined : VTApiPlaneraResaCoreModelsTransportSubModeFromJSON(json['transportSubMode']),
        'origin': !exists(json, 'origin') ? undefined : VTApiPlaneraResaWebV4ModelsJourneysCallApiModelFromJSON(json['origin']),
        'destination': !exists(json, 'destination') ? undefined : VTApiPlaneraResaWebV4ModelsJourneysCallApiModelFromJSON(json['destination']),
        'notes': !exists(json, 'notes') ? undefined : (json['notes'] === null ? null : (json['notes'] as Array<any>).map(VTApiPlaneraResaCoreModelsNoteFromJSON)),
        'distanceInMeters': !exists(json, 'distanceInMeters') ? undefined : json['distanceInMeters'],
        'plannedDepartureTime': !exists(json, 'plannedDepartureTime') ? undefined : json['plannedDepartureTime'],
        'plannedArrivalTime': !exists(json, 'plannedArrivalTime') ? undefined : json['plannedArrivalTime'],
        'plannedDurationInMinutes': !exists(json, 'plannedDurationInMinutes') ? undefined : json['plannedDurationInMinutes'],
        'estimatedDepartureTime': !exists(json, 'estimatedDepartureTime') ? undefined : json['estimatedDepartureTime'],
        'estimatedArrivalTime': !exists(json, 'estimatedArrivalTime') ? undefined : json['estimatedArrivalTime'],
        'estimatedDurationInMinutes': !exists(json, 'estimatedDurationInMinutes') ? undefined : json['estimatedDurationInMinutes'],
        'estimatedNumberOfSteps': !exists(json, 'estimatedNumberOfSteps') ? undefined : json['estimatedNumberOfSteps'],
        'linkCoordinates': !exists(json, 'linkCoordinates') ? undefined : (json['linkCoordinates'] === null ? null : (json['linkCoordinates'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsCoordinateApiModelFromJSON)),
        'segments': !exists(json, 'segments') ? undefined : (json['segments'] === null ? null : (json['segments'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModelFromJSON)),
        'journeyLegIndex': !exists(json, 'journeyLegIndex') ? undefined : json['journeyLegIndex'],
    };
}

export function VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneysConnectionLinkApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transportMode': VTApiPlaneraResaCoreModelsTransportModeToJSON(value.transportMode),
        'transportSubMode': VTApiPlaneraResaCoreModelsTransportSubModeToJSON(value.transportSubMode),
        'origin': VTApiPlaneraResaWebV4ModelsJourneysCallApiModelToJSON(value.origin),
        'destination': VTApiPlaneraResaWebV4ModelsJourneysCallApiModelToJSON(value.destination),
        'notes': value.notes === undefined ? undefined : (value.notes === null ? null : (value.notes as Array<any>).map(VTApiPlaneraResaCoreModelsNoteToJSON)),
        'distanceInMeters': value.distanceInMeters,
        'plannedDepartureTime': value.plannedDepartureTime,
        'plannedArrivalTime': value.plannedArrivalTime,
        'plannedDurationInMinutes': value.plannedDurationInMinutes,
        'estimatedDepartureTime': value.estimatedDepartureTime,
        'estimatedArrivalTime': value.estimatedArrivalTime,
        'estimatedDurationInMinutes': value.estimatedDurationInMinutes,
        'estimatedNumberOfSteps': value.estimatedNumberOfSteps,
        'linkCoordinates': value.linkCoordinates === undefined ? undefined : (value.linkCoordinates === null ? null : (value.linkCoordinates as Array<any>).map(VTApiPlaneraResaWebV4ModelsCoordinateApiModelToJSON)),
        'segments': value.segments === undefined ? undefined : (value.segments === null ? null : (value.segments as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModelToJSON)),
        'journeyLegIndex': value.journeyLegIndex,
    };
}

