/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VTApiPlaneraResaCoreModelsTimeLimitation = {
    Unknown: 'unknown',
    Heltid: 'heltid',
    Lagtrafik: 'lagtrafik',
    Skolkort04till19: 'skolkort04till19',
    Skolkort04till22: 'skolkort04till22',
    Skolkort04till1930: 'skolkort04till1930',
    Fritid100: 'fritid100',
    Fritidkomplement: 'fritidkomplement',
    Fritidvardag19till22: 'fritidvardag19till22',
    Fritidvardag14till24: 'fritidvardag14till24',
    Fritidkvallhelg: 'fritidkvallhelg',
    Fritidkvallhelglov: 'fritidkvallhelglov',
    Fritidjulsommarlov: 'fritidjulsommarlov',
    Fritidale: 'fritidale'
} as const;
export type VTApiPlaneraResaCoreModelsTimeLimitation = typeof VTApiPlaneraResaCoreModelsTimeLimitation[keyof typeof VTApiPlaneraResaCoreModelsTimeLimitation];


export function VTApiPlaneraResaCoreModelsTimeLimitationFromJSON(json: any): VTApiPlaneraResaCoreModelsTimeLimitation {
    return VTApiPlaneraResaCoreModelsTimeLimitationFromJSONTyped(json, false);
}

export function VTApiPlaneraResaCoreModelsTimeLimitationFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaCoreModelsTimeLimitation {
    return json as VTApiPlaneraResaCoreModelsTimeLimitation;
}

export function VTApiPlaneraResaCoreModelsTimeLimitationToJSON(value?: VTApiPlaneraResaCoreModelsTimeLimitation | null): any {
    return value as any;
}

