/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VTApiPlaneraResaCoreModelsTimeValidityType = {
    Unknown: 'unknown',
    Amountunit: 'amountunit',
    Fromtodate: 'fromtodate',
    Fromtodatetime: 'fromtodatetime'
} as const;
export type VTApiPlaneraResaCoreModelsTimeValidityType = typeof VTApiPlaneraResaCoreModelsTimeValidityType[keyof typeof VTApiPlaneraResaCoreModelsTimeValidityType];


export function VTApiPlaneraResaCoreModelsTimeValidityTypeFromJSON(json: any): VTApiPlaneraResaCoreModelsTimeValidityType {
    return VTApiPlaneraResaCoreModelsTimeValidityTypeFromJSONTyped(json, false);
}

export function VTApiPlaneraResaCoreModelsTimeValidityTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaCoreModelsTimeValidityType {
    return json as VTApiPlaneraResaCoreModelsTimeValidityType;
}

export function VTApiPlaneraResaCoreModelsTimeValidityTypeToJSON(value?: VTApiPlaneraResaCoreModelsTimeValidityType | null): any {
    return value as any;
}

