/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VTApiPlaneraResaCoreModelsTransportSubMode = {
    Unknown: 'unknown',
    None: 'none',
    Vasttagen: 'vasttagen',
    Longdistancetrain: 'longdistancetrain',
    Regionaltrain: 'regionaltrain'
} as const;
export type VTApiPlaneraResaCoreModelsTransportSubMode = typeof VTApiPlaneraResaCoreModelsTransportSubMode[keyof typeof VTApiPlaneraResaCoreModelsTransportSubMode];


export function VTApiPlaneraResaCoreModelsTransportSubModeFromJSON(json: any): VTApiPlaneraResaCoreModelsTransportSubMode {
    return VTApiPlaneraResaCoreModelsTransportSubModeFromJSONTyped(json, false);
}

export function VTApiPlaneraResaCoreModelsTransportSubModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaCoreModelsTransportSubMode {
    return json as VTApiPlaneraResaCoreModelsTransportSubMode;
}

export function VTApiPlaneraResaCoreModelsTransportSubModeToJSON(value?: VTApiPlaneraResaCoreModelsTransportSubMode | null): any {
    return value as any;
}

