/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaCoreModelsTransportMode } from './VTApiPlaneraResaCoreModelsTransportMode';
import {
    VTApiPlaneraResaCoreModelsTransportModeFromJSON,
    VTApiPlaneraResaCoreModelsTransportModeFromJSONTyped,
    VTApiPlaneraResaCoreModelsTransportModeToJSON,
} from './VTApiPlaneraResaCoreModelsTransportMode';
import type { VTApiPlaneraResaCoreModelsTransportSubMode } from './VTApiPlaneraResaCoreModelsTransportSubMode';
import {
    VTApiPlaneraResaCoreModelsTransportSubModeFromJSON,
    VTApiPlaneraResaCoreModelsTransportSubModeFromJSONTyped,
    VTApiPlaneraResaCoreModelsTransportSubModeToJSON,
} from './VTApiPlaneraResaCoreModelsTransportSubMode';

/**
 * Information about a line of a departure or arrival service journey.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel {
    /**
     * 16-digit Västtrafik line gid.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel
     */
    gid?: string | null;
    /**
     * The line name.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel
     */
    name?: string | null;
    /**
     * The short name of the line, usually 5 characters or less.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel
     */
    shortName?: string | null;
    /**
     * The designation of the line.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel
     */
    designation?: string | null;
    /**
     * The background color of the line symbol.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel
     */
    backgroundColor?: string | null;
    /**
     * The foreground color of the line symbol.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel
     */
    foregroundColor?: string | null;
    /**
     * The border color of the line symbol.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel
     */
    borderColor?: string | null;
    /**
     * 
     * @type {VTApiPlaneraResaCoreModelsTransportMode}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel
     */
    transportMode?: VTApiPlaneraResaCoreModelsTransportMode;
    /**
     * 
     * @type {VTApiPlaneraResaCoreModelsTransportSubMode}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel
     */
    transportSubMode?: VTApiPlaneraResaCoreModelsTransportSubMode;
    /**
     * Flag indicating if the line is wheelchair accessible.
     * @type {boolean}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel
     */
    isWheelchairAccessible?: boolean;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel {
    return VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gid': !exists(json, 'gid') ? undefined : json['gid'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'shortName': !exists(json, 'shortName') ? undefined : json['shortName'],
        'designation': !exists(json, 'designation') ? undefined : json['designation'],
        'backgroundColor': !exists(json, 'backgroundColor') ? undefined : json['backgroundColor'],
        'foregroundColor': !exists(json, 'foregroundColor') ? undefined : json['foregroundColor'],
        'borderColor': !exists(json, 'borderColor') ? undefined : json['borderColor'],
        'transportMode': !exists(json, 'transportMode') ? undefined : VTApiPlaneraResaCoreModelsTransportModeFromJSON(json['transportMode']),
        'transportSubMode': !exists(json, 'transportSubMode') ? undefined : VTApiPlaneraResaCoreModelsTransportSubModeFromJSON(json['transportSubMode']),
        'isWheelchairAccessible': !exists(json, 'isWheelchairAccessible') ? undefined : json['isWheelchairAccessible'],
    };
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gid': value.gid,
        'name': value.name,
        'shortName': value.shortName,
        'designation': value.designation,
        'backgroundColor': value.backgroundColor,
        'foregroundColor': value.foregroundColor,
        'borderColor': value.borderColor,
        'transportMode': VTApiPlaneraResaCoreModelsTransportModeToJSON(value.transportMode),
        'transportSubMode': VTApiPlaneraResaCoreModelsTransportSubModeToJSON(value.transportSubMode),
        'isWheelchairAccessible': value.isWheelchairAccessible,
    };
}

