/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VTApiPlaneraResaCoreModelsTransportMode = {
    Unknown: 'unknown',
    None: 'none',
    Tram: 'tram',
    Bus: 'bus',
    Ferry: 'ferry',
    Train: 'train',
    Taxi: 'taxi',
    Walk: 'walk',
    Bike: 'bike',
    Car: 'car'
} as const;
export type VTApiPlaneraResaCoreModelsTransportMode = typeof VTApiPlaneraResaCoreModelsTransportMode[keyof typeof VTApiPlaneraResaCoreModelsTransportMode];


export function VTApiPlaneraResaCoreModelsTransportModeFromJSON(json: any): VTApiPlaneraResaCoreModelsTransportMode {
    return VTApiPlaneraResaCoreModelsTransportModeFromJSONTyped(json, false);
}

export function VTApiPlaneraResaCoreModelsTransportModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaCoreModelsTransportMode {
    return json as VTApiPlaneraResaCoreModelsTransportMode;
}

export function VTApiPlaneraResaCoreModelsTransportModeToJSON(value?: VTApiPlaneraResaCoreModelsTransportMode | null): any {
    return value as any;
}

